/*
App Name: CWL Hardware
App Client: CWL Hardware
Author: James Bryant D. Espino
URL: https://github.com/Jamespino20
Last Update Date: May 26, 2026
*/

import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import bcrypt from "bcryptjs";
import { auditLogs } from "./seed-data/audit-logs";

const pool = new Pool({ connectionString: process.env.ANVILOS_DATABASE_URL! });
const prisma = new PrismaClient({
  adapter: new PrismaPg(pool),
});

async function main() {
  console.log("Clearing existing data...");
  await prisma.transactionItem.deleteMany();
  await prisma.transaction.deleteMany();
  await prisma.product.deleteMany();
  await prisma.supplier.deleteMany();
  await prisma.category.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.auditLog.deleteMany();
  await prisma.user.deleteMany();

  console.log("Seeding users...");
  const passwordJames = await bcrypt.hash("password123", 10);
  const passwordJane = await bcrypt.hash("password456", 10);
  const passwordJohn = await bcrypt.hash("password789", 10);

  await prisma.user.createMany({
    data: [
      {
        id: 1,
        sellerName: "James",
        username: "Jamespino",
        passwordHash: passwordJames,
        email: "espino.jamesbryant20@gmail.com",
        registryDate: new Date("2025-05-29"),
        lastLogin: new Date("2025-06-19 21:45:41"),
        isActive: true,
        role: "ADMIN",
        emailVerified: new Date("2025-05-29"),
      },
      {
        id: 4,
        sellerName: "Jane Doe",
        username: "janedo3",
        passwordHash: passwordJane,
        email: "janedo3@gmail.com",
        registryDate: new Date("2025-06-04"),
        lastLogin: new Date("2025-06-19 22:09:40"),
        isActive: true,
        role: "STAFF",
        emailVerified: new Date("2025-06-04"),
      },
      {
        id: 5,
        sellerName: "John Doe",
        username: "johndo3",
        passwordHash: passwordJohn,
        email: "johndo3@gmail.com",
        registryDate: new Date("2025-06-09"),
        lastLogin: new Date("2025-06-19 22:00:16"),
        isActive: true,
        role: "STAFF",
        emailVerified: new Date("2025-06-09"),
      },
    ],
  });

  console.log("Seeding categories...");
  await prisma.category.createMany({
    data: [
      {
        id: 1,
        name: "Hardware",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 2,
        name: "Lumber",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 3,
        name: "Wires",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 4,
        name: "Plywood",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-14 09:29:23"),
      },
      {
        id: 5,
        name: "Pipes",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-14 16:26:13"),
      },
      {
        id: 6,
        name: "Paints",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-14 16:26:27"),
      },
      {
        id: 7,
        name: "Bars",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-14 16:26:27"),
      },
      {
        id: 8,
        name: "Corneza",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 9,
        name: "T & G",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 10,
        name: "Door Jamb",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 11,
        name: "Liston",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 12,
        name: "G.I Sheets",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 13,
        name: "Electrical",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 14,
        name: "Plumbing",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-14 09:29:57"),
      },
      {
        id: 15,
        name: "Nails",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-14 09:29:57"),
      },
      {
        id: 16,
        name: "Chemicals",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 17,
        name: "Screws, Bolts, & Nuts",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-14 09:28:24"),
      },
      {
        id: 18,
        name: "Tools",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 19,
        name: "Solid Panel Door",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 20,
        name: "Solid Cabinet Door",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 21,
        name: "Flushdoor",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 22,
        name: "HDF Moulded Doors",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 23,
        name: "Drawer Face",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 24,
        name: "Ventilations",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 25,
        name: "Stair Component",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 26,
        name: "Laminated Wider Board",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 27,
        name: "Cabinet Door",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 28,
        name: "Carvings",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 29,
        name: "Toilet Accessories",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 30,
        name: "Insulation",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 31,
        name: "Wiring Devices",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-16 15:15:27"),
      },
      {
        id: 32,
        name: "Stock Files",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 33,
        name: "Sheridan",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 34,
        name: "Gulong",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-02 21:30:43"),
      },
      {
        id: 35,
        name: "Roofings",
        isAvailable: true,
        createdAt: new Date("2025-06-02 21:30:43"),
        updatedAt: new Date("2025-06-14 09:28:40"),
      },
      {
        id: 37,
        name: "Nuts",
        parentCategoryId: 17,
        isAvailable: true,
        createdAt: new Date("2025-06-07 18:07:52"),
        updatedAt: new Date("2025-06-14 17:14:01"),
      },
      {
        id: 38,
        name: "Screws",
        parentCategoryId: 17,
        isAvailable: true,
        createdAt: new Date("2025-06-07 21:26:59"),
        updatedAt: new Date("2025-06-16 15:15:27"),
      },
    ],
  });

  console.log("Seeding suppliers...");
  await prisma.supplier.createMany({
    data: [
      {
        id: 1,
        supplierName: "Top Silver Signal Marketing Inc.",
        contactName: "Aging",
        address: "137 RI Mc.Arthur Highway Tuktukan Guiginto Bulacan",
        isAvailable: true,
      },
      {
        id: 2,
        supplierName: "Megaworld Trading",
        contactName: "Jhenny delos Santos",
        isAvailable: true,
      },
      {
        id: 3,
        supplierName: "Orange Resources.Inc.",
        contactName: "James Son",
        address: "10 Gasan St., Masambong, SFDM, Quezon City",
        isAvailable: true,
      },
      {
        id: 4,
        supplierName: "Fourkings Lumber and Construction Supply",
        contactName: "Rene",
        email: "",
        address: "282 DRT Highway, Brgy. Bagong Nayon, Baliuag, Bulacan",
        isAvailable: true,
      },
      {
        id: 5,
        supplierName: "LPK Construction Supply Trading",
        contactName: "Joseph",
        address: "K-59 Anonas St. corner K-10, Project 2, Quezon City",
        isAvailable: true,
      },
      {
        id: 6,
        supplierName: "Golden Star Commercial",
        contactName: "James Son",
        address: "Road 1, Arty Subd., Brgy. Talipapa, Novaliches, Quezon City",
        isAvailable: true,
      },
      {
        id: 7,
        supplierName: "SHERIDAN MARKETING, INC",
        address: "74 De Jesus St., Brgy. San Antonio, SFDM, Quezon City",
        isAvailable: true,
      },
      {
        id: 8,
        supplierName: "Globe International Distributor Center INC.",
        address: "228 Roosevelt Avenue, Quezon City",
        isAvailable: true,
      },
      {
        id: 9,
        supplierName: "Four Silver Jade Trading Corp.",
        address:
          "Rm.713 Downtown Center Bldg., 516 Q. Paredes St., Binondo, Manila",
        isAvailable: true,
      },
      {
        id: 10,
        supplierName: "SOUDOWELD INDUSTRIAL PHILS.",
        address: "10 M.Antonio St. Maysan ,Valenzuela City",
        isAvailable: true,
      },
      {
        id: 11,
        supplierName: "R.O.H TRADING AND SERVICES",
        address: "131 Cagayan Valley Road, Taal, Pulilan, Bulacan",
        isAvailable: true,
      },
      {
        id: 12,
        supplierName: "Philippine HardwareHouse Co. Inc.",
        address: "2713 Zamora St., Brgy. 097, Pasay City",
        isAvailable: true,
      },
      {
        id: 13,
        supplierName: "ARTES MYER PHILIPPINES",
        contactName: "Lito De Leon",
        address: "57 Sgt. Rivera St, Quezon City, 1115 Metro Manila",
        isAvailable: true,
      },
      {
        id: 14,
        supplierName: "HISENSE TRADING",
        address:
          "112 Kanlaon St. Cor Simoun St., Sta. Mesa Heights, Quezon City",
        isAvailable: false,
      },
      {
        id: 15,
        supplierName: "GIVM CONCRETE PRODUCT",
        address: "San Rafael, Bulacan",
        isAvailable: true,
      },
      {
        id: 16,
        supplierName: "LIROBENSON HARDWARE",
        address: "2263 Sinaglong cor. A. Francisco, Malate, Manila",
        isAvailable: true,
      },
      {
        id: 17,
        supplierName: "DILCUE TRADING",
        address: "Malabon City",
        isAvailable: true,
      },
      {
        id: 18,
        supplierName: "MORNING BRIGHT WIRES AND CABLE MARKETING",
        address: "#80 Cenacle Drive, Sanville Subd., Brgy. Culiat, Quezon City",
        isAvailable: true,
      },
      {
        id: 19,
        supplierName: "M. AYROSO LUMBER AND HARDWARE",
        address: "9 Gov. Halili Ave., Ext., Binang 2nd, Bocaue, Bulacan",
        isAvailable: true,
      },
      {
        id: 20,
        supplierName: "VE Enterprises",
        address:
          "Blk. 14 Lot 30 Pomelo St. Rainbow Villa. 5 Bagumbong, Caloocan City",
        isAvailable: true,
      },
      {
        id: 21,
        supplierName: "Sea King Commercial",
        address:
          "9428 Urna Drive Corner Cecile St., Airport Village, Parañaque City",
        isAvailable: true,
      },
      {
        id: 22,
        supplierName: "Bo De Oro",
        address: "Hanga, Sta. Rita, Guiguinto, Bulacan",
        isAvailable: true,
      },
      {
        id: 23,
        supplierName: "Supertop Trading Inc.",
        contactName: "Mike Velarde",
        address: "41 E.porto Street Brgy Del monte SFDM,Quezon City",
        isAvailable: true,
      },
      {
        id: 24,
        supplierName: "FIREFLY ELECTRIC AND LIGHTNING CORPORATION",
        address: "Sky 1 Tower, Dasmarinas St., Binondo, Manila",
        isAvailable: true,
      },
      {
        id: 25,
        supplierName: "P.C.A.",
        address: "A&J Rosegold Compound, Circum Road, Cutcot, Angeles",
        isAvailable: true,
      },
      {
        id: 26,
        supplierName: "WT Commercial",
        address: "Valenzuela City",
        isAvailable: true,
      },
      {
        id: 27,
        supplierName: "DS COMMERCIAL",
        address: "Poblacion, San Miguel, Bulacan",
        isAvailable: true,
      },
      {
        id: 28,
        supplierName: "TAN SU AND SONS CORPORATION",
        contactName: "",
        address: "Bo. Tikay, Malolos, Bulacan",
        isAvailable: true,
      },
      { id: 29, supplierName: "RESTO", isAvailable: true },
      {
        id: 30,
        supplierName: "A.F. Bautista Lumber",
        address: "Poblacion, Pulilan, Bulacan",
        isAvailable: true,
      },
      {
        id: 31,
        supplierName: "New Samex Trading Eagle",
        contactName: "Archie",
        address: "San Ildefonso, Bulacan",
        isAvailable: true,
      },
      {
        id: 32,
        supplierName: "GIVM CONCRETE PIPE",
        address: "Sampaloc, San Rafael, Bulacan",
        isAvailable: true,
      },
      {
        id: 33,
        supplierName: "Uniprime Beaver ",
        address: "226 Sumulong Hi-way,Mambugan,Antipolo",
        isAvailable: true,
      },
      {
        id: 34,
        supplierName: "NEW Grace Enterprises",
        address: "Tierra Dayao, Sta. Cruz, Guiguinto, Bulacan",
        isAvailable: true,
      },
      {
        id: 35,
        supplierName: "PARPIPES CONCRETE PRODUCTS CORP.",
        contactName: "Ms. Oya",
        address: "KM 38, Pulong Buhangin, Sta. Maria, Bulacan",
        isAvailable: true,
      },
      {
        id: 36,
        supplierName: "Caltex Pulilan",
        contactName: "Mr. John Luna",
        address: "Sto. Cristo, Pulilan, Bulacan",
        isAvailable: true,
      },
    ],
  });

  console.log("Seeding products...");
  await prisma.product.createMany({
    data: [
      {
        id: 1,
        productName: "Muriatic Acid",
        categoryId: 16,
        category: "Chemicals",
        supplierId: 8,
        supplierName: "Globe International Distributor Center INC.",
        unitPrice: 195.0,
        quantity: 110,
        minThreshold: 20,
        isAvailable: true,
        createdAt: new Date("2025-06-16 15:14:01"),
      },
      {
        id: 2,
        productName: "Sheridan 1",
        categoryId: 33,
        category: "Sheridan",
        supplierId: 7,
        supplierName: "SHERIDAN MARKETING, INC",
        unitPrice: 43.0,
        quantity: 40,
        minThreshold: 3,
        isAvailable: true,
        createdAt: new Date("2025-06-16 15:14:01"),
      },
      {
        id: 3,
        productName: "huh?",
        categoryId: 7,
        category: "Bars",
        supplierId: 28,
        supplierName: "TAN SU AND SONS CORPORATION",
        unitPrice: 54.0,
        quantity: 33,
        minThreshold: 13,
        isAvailable: true,
        createdAt: new Date("2025-06-16 15:14:01"),
      },
      {
        id: 4,
        productName: "Hello?",
        categoryId: 7,
        category: "Bars",
        supplierId: 30,
        supplierName: "A.F. Bautista Lumber",
        unitPrice: 45.0,
        quantity: 23,
        minThreshold: 10,
        isAvailable: true,
        createdAt: new Date("2025-06-16 15:14:01"),
      },
      {
        id: 506,
        productName: "2x2 Screws",
        categoryId: 38,
        category: "Screws, Bolts, & Nuts (Screws)",
        supplierId: 22,
        supplierName: "Bo De Oro",
        unitPrice: 10.0,
        quantity: 49,
        minThreshold: 100,
        isAvailable: false,
        createdAt: new Date("2025-06-16 15:14:01"),
      },
      {
        id: 507,
        productName: "2z2 Screws",
        categoryId: 38,
        category: "Screws, Bolts, & Nuts (Screws)",
        supplierId: 17,
        supplierName: "DILCUE TRADING",
        unitPrice: 15.0,
        quantity: 0,
        minThreshold: 20,
        isAvailable: false,
        createdAt: new Date("2025-06-16 15:14:01"),
      },
      {
        id: 508,
        productName: "JCBP",
        categoryId: 15,
        category: "Nails",
        supplierId: 31,
        supplierName: "New Samex Trading Eagle",
        unitPrice: 15.0,
        quantity: 100,
        minThreshold: 100,
        isAvailable: true,
        createdAt: new Date("2025-06-16 15:14:01"),
      },
      {
        id: 509,
        productName: "jcbp",
        categoryId: 7,
        category: "Bars",
        supplierId: 30,
        supplierName: "A.F. Bautista Lumber",
        unitPrice: 50.0,
        quantity: 0,
        minThreshold: 100,
        isAvailable: false,
        createdAt: new Date("2025-06-16 15:14:01"),
      },
    ],
  });

  console.log("Seeding transactions...");
  await prisma.transaction.createMany({
    data: [
      {
        id: 1,
        receiptNumber: 0,
        buyerName: "James Bryant Espino",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SaleWalkIn",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-05-30"),
        grandTotal: 195.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 2,
        receiptNumber: 0,
        buyerName: "James Bryant Espino",
        sellerId: 1,
        sellerName: "James",
        transactionType: "Return",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-05-30"),
        grandTotal: 195.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 3,
        receiptNumber: 0,
        buyerName: "James Bryant Espino",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SaleWalkIn",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-05-30"),
        grandTotal: 195.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 4,
        receiptNumber: 0,
        buyerName: "James Bryant Espino",
        sellerId: 1,
        sellerName: "James",
        transactionType: "Return",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-05-30"),
        grandTotal: 195.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 5,
        receiptNumber: 0,
        buyerName: "James",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SaleWalkIn",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-05-30"),
        grandTotal: 238.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 6,
        receiptNumber: 0,
        buyerName: "James",
        sellerId: 1,
        sellerName: "James",
        transactionType: "Return",
        deliveryMethod: "WalkIn",
        transactionStatus: "Cancelled",
        transactionDate: new Date("2025-05-30"),
        grandTotal: 238.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 7,
        receiptNumber: 0,
        buyerName: "James",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SalePO",
        deliveryMethod: "Delivery",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-05-30"),
        grandTotal: 15210.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 8,
        receiptNumber: 0,
        buyerName: "delulu",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SaleWalkIn",
        deliveryMethod: "WalkIn",
        transactionStatus: "Cancelled",
        transactionDate: new Date("2025-05-30"),
        grandTotal: 195.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 200,
        receiptNumber: 0,
        buyerName: "Jackson",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SalePO",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-08"),
        grandTotal: 15.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 201,
        receiptNumber: 0,
        buyerName: "Jackson",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SalePO",
        deliveryMethod: "WalkIn",
        transactionStatus: "Ongoing",
        transactionDate: new Date("2025-06-08"),
        grandTotal: 10.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 202,
        receiptNumber: 0,
        buyerName: "Jackson",
        sellerId: 1,
        sellerName: "James",
        transactionType: "Return",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-08"),
        grandTotal: 15.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 203,
        receiptNumber: 0,
        buyerName: "Jackson",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SalePO",
        deliveryMethod: "WalkIn",
        transactionStatus: "Ongoing",
        transactionDate: new Date("2025-06-08"),
        grandTotal: 10.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 204,
        receiptNumber: 0,
        buyerName: "eeee",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SaleWalkIn",
        deliveryMethod: "Delivery",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-09"),
        grandTotal: 43.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 205,
        receiptNumber: 0,
        buyerName: "benken",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SalePO",
        deliveryMethod: "COD",
        transactionStatus: "Cancelled",
        transactionDate: new Date("2025-06-14"),
        grandTotal: 150.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 206,
        receiptNumber: 0,
        buyerName: "eeee",
        sellerId: 1,
        sellerName: "James",
        transactionType: "Return",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-14"),
        grandTotal: 43.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 207,
        receiptNumber: 0,
        buyerName: "cccc",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SaleWalkIn",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-14"),
        grandTotal: 43.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 208,
        receiptNumber: 0,
        buyerName: "cccc",
        sellerId: 1,
        sellerName: "James",
        transactionType: "Return",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-14"),
        grandTotal: 43.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 209,
        receiptNumber: 0,
        buyerName: "cccc",
        sellerId: 1,
        sellerName: "James",
        transactionType: "Return",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-14"),
        grandTotal: 215.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 210,
        receiptNumber: 0,
        buyerName: "cccc",
        sellerId: 1,
        sellerName: "James",
        transactionType: "SaleWalkIn",
        deliveryMethod: "Pickup",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-14"),
        grandTotal: 405.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 211,
        receiptNumber: 0,
        buyerName: "benken",
        sellerId: 4,
        sellerName: "Jane Doe",
        transactionType: "SaleWalkIn",
        deliveryMethod: "Pickup",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-14"),
        grandTotal: 450.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 212,
        receiptNumber: 0,
        buyerName: "ken",
        sellerId: 4,
        sellerName: "Jane Doe",
        transactionType: "SaleWalkIn",
        deliveryMethod: "Pickup",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-14"),
        grandTotal: 500.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 213,
        receiptNumber: 22351994,
        buyerName: "benken",
        sellerId: 5,
        sellerName: "John Doe",
        transactionType: "SaleWalkIn",
        deliveryMethod: "Pickup",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-16"),
        grandTotal: 390.0,
        createdAt: null,
        isReturned: false,
      },
      {
        id: 214,
        receiptNumber: 66775131,
        buyerName: "benken",
        sellerId: 4,
        sellerName: "Jane Doe",
        transactionType: "SaleWalkIn",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-16"),
        grandTotal: 490.0,
        createdAt: null,
        isReturned: true,
        returnForReceiptNumber: 10797722,
      },
      {
        id: 215,
        receiptNumber: 10797722,
        buyerName: "benken",
        sellerId: 1,
        sellerName: "James",
        transactionType: "Return",
        deliveryMethod: "WalkIn",
        transactionStatus: "Completed",
        transactionDate: new Date("2025-06-16"),
        grandTotal: 490.0,
        createdAt: null,
        isReturned: true,
        returnForReceiptNumber: 10797722,
      },
    ],
  });

  console.log("Seeding transaction items...");
  await prisma.transactionItem.createMany({
    data: [
      {
        id: 13,
        transactionId: 2,
        productId: 1,
        productName: "Muriatic Acid",
        quantity: 1,
        unitPrice: 195.0,
        totalPrice: 195.0,
      },
      {
        id: 14,
        transactionId: 3,
        productId: 1,
        productName: "Muriatic Acid",
        quantity: 1,
        unitPrice: 195.0,
        totalPrice: 195.0,
      },
      {
        id: 15,
        transactionId: 4,
        productId: 1,
        productName: "Muriatic Acid",
        quantity: 1,
        unitPrice: 195.0,
        totalPrice: 195.0,
      },
      {
        id: 16,
        transactionId: 5,
        productId: 1,
        productName: "Muriatic Acid",
        quantity: 1,
        unitPrice: 195.0,
        totalPrice: 195.0,
      },
      {
        id: 17,
        transactionId: 5,
        productId: 2,
        productName: "Sheridan 1",
        quantity: 1,
        unitPrice: 43.0,
        totalPrice: 43.0,
      },
      {
        id: 21,
        transactionId: 8,
        productId: 1,
        productName: "Muriatic Acid",
        quantity: 1,
        unitPrice: 195.0,
        totalPrice: 195.0,
      },
      {
        id: 28,
        transactionId: 1,
        productId: 1,
        productName: "Muriatic Acid",
        quantity: 1,
        unitPrice: 195.0,
        totalPrice: 195.0,
      },
      {
        id: 32,
        transactionId: 6,
        productId: 2,
        productName: "Sheridan 1",
        quantity: 1,
        unitPrice: 43.0,
        totalPrice: 43.0,
      },
      {
        id: 33,
        transactionId: 6,
        productId: 1,
        productName: "Muriatic Acid",
        quantity: 1,
        unitPrice: 195.0,
        totalPrice: 195.0,
      },
      {
        id: 41,
        transactionId: 7,
        productId: 1,
        productName: "Muriatic Acid",
        quantity: 78,
        unitPrice: 195.0,
        totalPrice: 15210.0,
      },
      {
        id: 49,
        transactionId: 202,
        productId: 507,
        productName: "2z2 Screws",
        quantity: 1,
        unitPrice: 15.0,
        totalPrice: 15.0,
      },
      {
        id: 55,
        transactionId: 201,
        productId: 506,
        productName: "2x2 Screws",
        quantity: 1,
        unitPrice: 10.0,
        totalPrice: 10.0,
      },
      {
        id: 65,
        transactionId: 203,
        productId: 506,
        productName: "2x2 Screws",
        quantity: 1,
        unitPrice: 10.0,
        totalPrice: 10.0,
      },
      {
        id: 66,
        transactionId: 204,
        productId: 2,
        productName: "Sheridan 1",
        quantity: 1,
        unitPrice: 43.0,
        totalPrice: 43.0,
      },
      {
        id: 67,
        transactionId: 200,
        productId: 507,
        productName: "2z2 Screws",
        quantity: 1,
        unitPrice: 15.0,
        totalPrice: 15.0,
      },
      {
        id: 69,
        transactionId: 205,
        productId: 506,
        productName: "2x2 Screws",
        quantity: 15,
        unitPrice: 10.0,
        totalPrice: 150.0,
      },
      {
        id: 70,
        transactionId: 206,
        productId: 2,
        productName: "Sheridan 1",
        quantity: 1,
        unitPrice: 43.0,
        totalPrice: 43.0,
      },
      {
        id: 71,
        transactionId: 207,
        productId: 2,
        productName: "Sheridan 1",
        quantity: 1,
        unitPrice: 43.0,
        totalPrice: 43.0,
      },
      {
        id: 72,
        transactionId: 208,
        productId: 2,
        productName: "Sheridan 1",
        quantity: 1,
        unitPrice: 43.0,
        totalPrice: 43.0,
      },
      {
        id: 73,
        transactionId: 209,
        productId: 2,
        productName: "Sheridan 1",
        quantity: 1,
        unitPrice: 43.0,
        totalPrice: 43.0,
      },
      {
        id: 74,
        transactionId: 210,
        productId: 4,
        productName: "Hello?",
        quantity: 9,
        unitPrice: 45.0,
        totalPrice: 405.0,
      },
      {
        id: 75,
        transactionId: 211,
        productId: 4,
        productName: "Hello?",
        quantity: 10,
        unitPrice: 45.0,
        totalPrice: 450.0,
      },
      {
        id: 76,
        transactionId: 212,
        productId: 509,
        productName: "jcbp",
        quantity: 10,
        unitPrice: 50.0,
        totalPrice: 500.0,
      },
      {
        id: 77,
        transactionId: 213,
        productId: 4,
        productName: "Hello?",
        quantity: 3,
        unitPrice: 45.0,
        totalPrice: 135.0,
      },
      {
        id: 78,
        transactionId: 213,
        productId: 507,
        productName: "2z2 Screws",
        quantity: 17,
        unitPrice: 15.0,
        totalPrice: 255.0,
      },
      {
        id: 79,
        transactionId: 214,
        productId: 506,
        productName: "2x2 Screws",
        quantity: 49,
        unitPrice: 10.0,
        totalPrice: 490.0,
      },
      {
        id: 80,
        transactionId: 215,
        productId: 506,
        productName: "2x2 Screws",
        quantity: 49,
        unitPrice: 10.0,
        totalPrice: 490.0,
      },
    ],
  });

  console.log("Seeding notifications...");
  await prisma.notification.createMany({
    data: [
      {
        id: 1,
        systemNotification: "Stock_506",
        message: "LOW STOCK: 2x2 Screws quantity is 49 (threshold: 100)",
        createdAt: new Date("2025-06-10 22:09:48"),
      },
      {
        id: 2,
        systemNotification: "Stock_507",
        message: "LOW STOCK: 2z2 Screws quantity is 17 (threshold: 20)",
        createdAt: new Date("2025-06-10 22:09:48"),
      },
      {
        id: 3,
        systemNotification: "Transaction_201",
        message: "Ongoing transaction: #201 with Jackson",
        createdAt: new Date("2025-06-08"),
      },
      {
        id: 4,
        systemNotification: "Transaction_203",
        message: "Ongoing transaction: #203 with Jackson",
        createdAt: new Date("2025-06-08"),
      },
      {
        id: 5,
        systemNotification: "Stock_508",
        message: "LOW STOCK: JCBP quantity is 100 (threshold: 100)",
        createdAt: new Date("2025-06-14 09:32:45"),
      },
      {
        id: 6,
        systemNotification: "Transaction_205",
        message: "Ongoing transaction: #205 with benken",
        createdAt: new Date("2025-06-14"),
      },
      {
        id: 7,
        systemNotification: "Stock_509",
        message: "LOW STOCK: jcbp quantity is 10 (threshold: 100)",
        createdAt: new Date("2025-06-14 17:16:47"),
      },
      {
        id: 8,
        systemNotification: "Stock_509",
        message: "NO STOCK: jcbp is out of stock!",
        createdAt: new Date("2025-06-14 17:25:31"),
      },
      {
        id: 9,
        systemNotification: "Stock_508",
        message: "NO STOCK: JCBP is out of stock!",
        createdAt: new Date("2025-06-16 14:14:40"),
      },
      {
        id: 10,
        systemNotification: "Stock_1",
        message: "NO STOCK: Muriatic Acid is out of stock!",
        createdAt: new Date("2025-06-16 14:25:20"),
      },
      {
        id: 11,
        systemNotification: "Stock_522",
        message: "LOW STOCK: JCBP quantity is 100 (threshold: 100)",
        createdAt: new Date("2025-06-16 14:35:32"),
      },
      {
        id: 12,
        systemNotification: "Stock_523",
        message: "NO STOCK: jcbp is out of stock!",
        createdAt: new Date("2025-06-16 14:35:32"),
      },
      {
        id: 13,
        systemNotification: "Stock_530",
        message: "LOW STOCK: JCBP quantity is 100 (threshold: 100)",
        createdAt: new Date("2025-06-16 14:46:29"),
      },
      {
        id: 14,
        systemNotification: "Stock_531",
        message: "NO STOCK: jcbp is out of stock!",
        createdAt: new Date("2025-06-16 14:46:29"),
      },
      {
        id: 15,
        systemNotification: "Stock_538",
        message: "LOW STOCK: JCBP quantity is 100 (threshold: 100)",
        createdAt: new Date("2025-06-16 14:52:56"),
      },
      {
        id: 16,
        systemNotification: "Stock_539",
        message: "NO STOCK: jcbp is out of stock!",
        createdAt: new Date("2025-06-16 14:52:56"),
      },
      {
        id: 17,
        systemNotification: "Stock_507",
        message: "NO STOCK: 2z2 Screws is out of stock!",
        createdAt: new Date("2025-06-16 20:01:09"),
      },
      {
        id: 18,
        systemNotification: "Stock_506",
        message: "NO STOCK: 2x2 Screws is out of stock!",
        createdAt: new Date("2025-06-16 20:02:50"),
      },
    ],
  });

  console.log(`Seeding ${auditLogs.length} audit log entries...`);
  const BATCH = 50;
  for (let i = 0; i < auditLogs.length; i += BATCH) {
    const batch = auditLogs.slice(i, i + BATCH);
    const safe = batch.map((r) => ({
      id: r.id,
      sellerId: r.sellerId ?? null,
      logTime: new Date(
        new Date(r.logTime ?? new Date()).getTime() +
          Math.floor(Math.random() * 999),
      ),
      successStatus: r.successStatus,
      panel: r.panel ?? null,
      action: r.action ?? null,
      details: r.details ?? null,
    }));
    await prisma.auditLog.createMany({ data: safe });
    process.stdout.write(
      `\r  audit logs: ${Math.min(i + BATCH, auditLogs.length)}/${auditLogs.length}`,
    );
  }
  console.log("");

  // Reset PostgreSQL sequences to avoid unique constraint conflicts
  console.log("Resetting sequences...");
  const tableCols: [string, string][] = [
    ["users", "SELLER_ID"],
    ["suppliers", "SUPPLIER_ID"],
    ["products", "PRODUCT_ID"],
    ["categories", "CATEGORY_ID"],
    ["transactions", "TRANSACTION_ID"],
    ["notifications", "NOTIFICATION_ID"],
    ["audit_log", "LOG_ID"],
    ["transaction_items", "ITEM_ID"],
  ];
  for (const [table, col] of tableCols) {
    await prisma.$executeRawUnsafe(
      `SELECT setval(pg_get_serial_sequence($1, $2), COALESCE((SELECT MAX("${col}") FROM "${table}"), 1))`,
      table,
      col,
    );
  }

  console.log("Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
